Repository honeycombio/buildevents, pull requests merged in 2021-11, with the labels that each got.

#119 Allow specifying an alternative shell
  README.md
  cmd_cmd.go
Labels: type: enhancement, version: bump minor

#121 Bump libhoney-go to v1.15.6
  go.mod
  go.sum
Labels: type: maintenance, version: bump patch

#122 Prepare v0.7.0 release
  CHANGELOG.md
  RELEASING.md
Labels: type: maintenance, version: bump minor

#124 Create draft GitHub release during publish
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#126 do not fail the build if buildURL does not verify API key
  cmd_watch.go
Labels: version: bump patch

#128 Fix release publish
  .circleci/config.yml
Labels: type: maintenance, version: no bump
