Repository honeycombio/buildevents, pull requests merged in 2022-01, with the labels that each got.

#136 Prepare v0.7.2 release
  CHANGELOG.md
Labels: type: maintenance, version: bump patch

#137 Return underlying exit code when running commands
  main.go
Labels: type: enhancement, version: bump minor

#138 prepare 0.8.0 release
  CHANGELOG.md
Labels: type: maintenance, version: bump minor
