Repository honeycombio/buildevents, pull requests merged in 2022-04, with the labels that each got.

#146 Support E&S
  CHANGELOG.md
  README.md
  cmd_build.go
  cmd_cmd.go
  cmd_root.go
  cmd_step.go
  cmd_watch.go
  common.go
  go.mod
  go.sum
  main.go
Labels: type: enhancement, version: bump minor

#148 remove erroneous default value
  cmd_root.go
Labels: version: bump patch

#150 maint: update ci image to cimg/go:1.18
  .circleci/config.yml
Labels: type: maintenance, version: no bump, version: bump patch
